# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_mapping_status_command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.backend_to_device_message_meta_pb2 as backend__to__device__message__meta__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#update_mapping_status_command.proto\x12.com.bosch.bfb.protobuf.devicevehiclemapping.v2\x1a$backend_to_device_message_meta.proto\"\xa8\x01\n\x1aUpdateMappingStatusCommand\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.BackendToDeviceMessageMeta\x12\\\n\rmappingStatus\x18\xa1\xfb\xbd\xa0\x01 \x01(\x0e\x32\x41.com.bosch.bfb.protobuf.devicevehiclemapping.v2.MappingStatusEnum*L\n\x11MappingStatusEnum\x12\x10\n\x0cVIN_RECEIVED\x10\x00\x12\n\n\x06MAPPED\x10\x01\x12\x0c\n\x08UNMAPPED\x10\x02\x12\x0b\n\x07\x46\x41ILURE\x10\x03P\x00\x62\x06proto3')

_MAPPINGSTATUSENUM = DESCRIPTOR.enum_types_by_name['MappingStatusEnum']
MappingStatusEnum = enum_type_wrapper.EnumTypeWrapper(_MAPPINGSTATUSENUM)
VIN_RECEIVED = 0
MAPPED = 1
UNMAPPED = 2
FAILURE = 3


_UPDATEMAPPINGSTATUSCOMMAND = DESCRIPTOR.message_types_by_name['UpdateMappingStatusCommand']
UpdateMappingStatusCommand = _reflection.GeneratedProtocolMessageType('UpdateMappingStatusCommand', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMAPPINGSTATUSCOMMAND,
  '__module__' : 'update_mapping_status_command_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.devicevehiclemapping.v2.UpdateMappingStatusCommand)
  })
_sym_db.RegisterMessage(UpdateMappingStatusCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPPINGSTATUSENUM._serialized_start=296
  _MAPPINGSTATUSENUM._serialized_end=372
  _UPDATEMAPPINGSTATUSCOMMAND._serialized_start=126
  _UPDATEMAPPINGSTATUSCOMMAND._serialized_end=294
# @@protoc_insertion_point(module_scope)
