# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vin_update_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



import src.resources.proto_py.device_to_backend_message_meta_pb2 as device__to__backend__message__meta__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16vin_update_event.proto\x12.com.bosch.bfb.protobuf.devicevehiclemapping.v2\x1a$device_to_backend_message_meta.proto\"g\n\x0eVinUpdateEvent\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.DeviceToBackendMessageMeta\x12\r\n\x03vin\x18\x9b\x90\x07 \x01(\t\x12\x18\n\x0cvinIsTrusted\x18\xf0\xba\xf1\xa2\x01 \x01(\x08P\x00\x62\x06proto3')



_VINUPDATEEVENT = DESCRIPTOR.message_types_by_name['VinUpdateEvent']
VinUpdateEvent = _reflection.GeneratedProtocolMessageType('VinUpdateEvent', (_message.Message,), {
  'DESCRIPTOR' : _VINUPDATEEVENT,
  '__module__' : 'vin_update_event_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.devicevehiclemapping.v2.VinUpdateEvent)
  })
_sym_db.RegisterMessage(VinUpdateEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VINUPDATEEVENT._serialized_start=112
  _VINUPDATEEVENT._serialized_end=215
# @@protoc_insertion_point(module_scope)
