# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: certificate_report_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.device_to_backend_message_meta_pb2 as device__to__backend__message__meta__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63\x65rtificate_report_event.proto\x12*com.bosch.bfb.protobuf.devicemanagement.v2\x1a$device_to_backend_message_meta.proto\"\x9e\x01\n\x16\x43\x65rtificateReportEvent\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.DeviceToBackendMessageMeta\x12V\n\x0c\x63\x65rtificates\x18\xbc\xe3\xa3\xbc\x01 \x03(\x0b\x32<.com.bosch.bfb.protobuf.devicemanagement.v2.CertificateEntry\"x\n\x10\x43\x65rtificateEntry\x12K\n\x07purpose\x18\xe2\x85\x90i \x01(\x0e\x32\x37.com.bosch.bfb.protobuf.devicemanagement.v2.PurposeEnum\x12\x17\n\x0b\x63\x65rtificate\x18\x9a\x83\xfd\xa2\x01 \x01(\t*T\n\x0bPurposeEnum\x12\x13\n\x0fUNKNOWN_PURPOSE\x10\x00\x12\x17\n\x13\x42\x46\x42_CLIENT_TLS_AUTH\x10\x01\x12\x17\n\x13\x41RTIFACT_ENCRYPTION\x10\x02P\x00\x62\x06proto3')

_PURPOSEENUM = DESCRIPTOR.enum_types_by_name['PurposeEnum']
PurposeEnum = enum_type_wrapper.EnumTypeWrapper(_PURPOSEENUM)
UNKNOWN_PURPOSE = 0
BFB_CLIENT_TLS_AUTH = 1
ARTIFACT_ENCRYPTION = 2


_CERTIFICATEREPORTEVENT = DESCRIPTOR.message_types_by_name['CertificateReportEvent']
_CERTIFICATEENTRY = DESCRIPTOR.message_types_by_name['CertificateEntry']
CertificateReportEvent = _reflection.GeneratedProtocolMessageType('CertificateReportEvent', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATEREPORTEVENT,
  '__module__' : 'certificate_report_event_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.devicemanagement.v2.CertificateReportEvent)
  })
_sym_db.RegisterMessage(CertificateReportEvent)

CertificateEntry = _reflection.GeneratedProtocolMessageType('CertificateEntry', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATEENTRY,
  '__module__' : 'certificate_report_event_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.devicemanagement.v2.CertificateEntry)
  })
_sym_db.RegisterMessage(CertificateEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PURPOSEENUM._serialized_start=399
  _PURPOSEENUM._serialized_end=483
  _CERTIFICATEREPORTEVENT._serialized_start=117
  _CERTIFICATEREPORTEVENT._serialized_end=275
  _CERTIFICATEENTRY._serialized_start=277
  _CERTIFICATEENTRY._serialized_end=397
# @@protoc_insertion_point(module_scope)
