# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_gps_status_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.backend_to_device_message_meta_pb2 as backend__to__device__message__meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cset_gps_status_command.proto\x1a$backend_to_device_message_meta.proto\"X\n\x13SetGpsStatusCommand\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.BackendToDeviceMessageMeta\x12\x13\n\x08gpsState\x18\xfb\xc3\x9f\x35 \x01(\x08P\x00\x62\x06proto3')



_SETGPSSTATUSCOMMAND = DESCRIPTOR.message_types_by_name['SetGpsStatusCommand']
SetGpsStatusCommand = _reflection.GeneratedProtocolMessageType('SetGpsStatusCommand', (_message.Message,), {
  'DESCRIPTOR' : _SETGPSSTATUSCOMMAND,
  '__module__' : 'set_gps_status_command_pb2'
  # @@protoc_insertion_point(class_scope:SetGpsStatusCommand)
  })
_sym_db.RegisterMessage(SetGpsStatusCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETGPSSTATUSCOMMAND._serialized_start=70
  _SETGPSSTATUSCOMMAND._serialized_end=158
# @@protoc_insertion_point(module_scope)
