# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: activate_measurement_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.backend_to_device_message_meta_pb2 as backend__to__device__message__meta__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"activate_measurement_command.proto\x12%com.bosch.bfb.protobuf.vehicledata.v3\x1a$backend_to_device_message_meta.proto\"\xa0\x01\n\x1a\x41\x63tivateMeasurementCommand\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.BackendToDeviceMessageMeta\x12\x19\n\rserialization\x18\xf1\xd7\x83\xb8\x01 \x01(\t\x12#\n\x18measurementConfiguration\x18\x9b\xf5\xee\x13 \x01(\t\x12\x14\n\tstackType\x18\xe5\x83\xf9\x37 \x01(\tP\x00\x62\x06proto3')



_ACTIVATEMEASUREMENTCOMMAND = DESCRIPTOR.message_types_by_name['ActivateMeasurementCommand']
ActivateMeasurementCommand = _reflection.GeneratedProtocolMessageType('ActivateMeasurementCommand', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATEMEASUREMENTCOMMAND,
  '__module__' : 'activate_measurement_command_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.vehicledata.v3.ActivateMeasurementCommand)
  })
_sym_db.RegisterMessage(ActivateMeasurementCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVATEMEASUREMENTCOMMAND._serialized_start=116
  _ACTIVATEMEASUREMENTCOMMAND._serialized_end=276
# @@protoc_insertion_point(module_scope)
