# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deactivate_measurement_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.backend_to_device_message_meta_pb2 as backend__to__device__message__meta__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$deactivate_measurement_command.proto\x12%com.bosch.bfb.protobuf.vehicledata.v3\x1a$backend_to_device_message_meta.proto\"o\n\x1c\x44\x65\x61\x63tivateMeasurementCommand\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.BackendToDeviceMessageMeta\x12!\n\x15measurementIdentifier\x18\xfb\xac\xd4\xfa\x01 \x01(\tP\x00\x62\x06proto3')



_DEACTIVATEMEASUREMENTCOMMAND = DESCRIPTOR.message_types_by_name['DeactivateMeasurementCommand']
DeactivateMeasurementCommand = _reflection.GeneratedProtocolMessageType('DeactivateMeasurementCommand', (_message.Message,), {
  'DESCRIPTOR' : _DEACTIVATEMEASUREMENTCOMMAND,
  '__module__' : 'deactivate_measurement_command_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.vehicledata.v3.DeactivateMeasurementCommand)
  })
_sym_db.RegisterMessage(DeactivateMeasurementCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEACTIVATEMEASUREMENTCOMMAND._serialized_start=117
  _DEACTIVATEMEASUREMENTCOMMAND._serialized_end=228
# @@protoc_insertion_point(module_scope)
