# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement_status_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import src.resources.proto_py.backend_to_device_message_meta_pb2 as backend__to__device__message__meta__pb2

import src.resources.proto_py.vehicleData.status_pb2 as status__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emeasurement_status_event.proto\x12%com.bosch.bfb.protobuf.vehicledata.v3\x1a$device_to_backend_message_meta.proto\x1a\x0cstatus.proto\"\xb9\x01\n\x16MeasurementStatusEvent\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.DeviceToBackendMessageMeta\x12\x41\n\x06status\x18\x8f\xe0\xc8\xa9\x01 \x01(\x0e\x32-.com.bosch.bfb.protobuf.vehicledata.v3.Status\x12\x15\n\terrorCode\x18\x95\xe0\xf2\x9c\x01 \x01(\t\x12\x17\n\x0c\x65rrorMessage\x18\xe1\xd9\xdf= \x01(\tP\x00P\x01\x62\x06proto3')



_MEASUREMENTSTATUSEVENT = DESCRIPTOR.message_types_by_name['MeasurementStatusEvent']
MeasurementStatusEvent = _reflection.GeneratedProtocolMessageType('MeasurementStatusEvent', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTSTATUSEVENT,
  '__module__' : 'measurement_status_event_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.vehicledata.v3.MeasurementStatusEvent)
  })
_sym_db.RegisterMessage(MeasurementStatusEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEASUREMENTSTATUSEVENT._serialized_start=126
  _MEASUREMENTSTATUSEVENT._serialized_end=311
# @@protoc_insertion_point(module_scope)
