# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend_to_device_message_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$backend_to_device_message_meta.proto\"J\n\x1a\x42\x61\x63kendToDeviceMessageMeta\x12\x16\n\nactivityId\x18\x8d\xe9\xed\xd0\x01 \x01(\t\x12\x14\n\ttimestamp\x18\x96\xd2\xa4\x1a \x01(\x03\x62\x06proto3')



_BACKENDTODEVICEMESSAGEMETA = DESCRIPTOR.message_types_by_name['BackendToDeviceMessageMeta']
BackendToDeviceMessageMeta = _reflection.GeneratedProtocolMessageType('BackendToDeviceMessageMeta', (_message.Message,), {
  'DESCRIPTOR' : _BACKENDTODEVICEMESSAGEMETA,
  '__module__' : 'backend_to_device_message_meta_pb2'
  # @@protoc_insertion_point(class_scope:BackendToDeviceMessageMeta)
  })
_sym_db.RegisterMessage(BackendToDeviceMessageMeta)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKENDTODEVICEMESSAGEMETA._serialized_start=40
  _BACKENDTODEVICEMESSAGEMETA._serialized_end=114
# @@protoc_insertion_point(module_scope)
