# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_to_backend_message_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$device_to_backend_message_meta.proto\"l\n\x1a\x44\x65viceToBackendMessageMeta\x12\x16\n\nactivityId\x18\x8d\xe9\xed\xd0\x01 \x01(\t\x12 \n\x15\x64\x65viceSequenceCounter\x18\xbe\xe4\xe4- \x01(\x05\x12\x14\n\ttimestamp\x18\x96\xd2\xa4\x1a \x01(\x03\x62\x06proto3')



_DEVICETOBACKENDMESSAGEMETA = DESCRIPTOR.message_types_by_name['DeviceToBackendMessageMeta']
DeviceToBackendMessageMeta = _reflection.GeneratedProtocolMessageType('DeviceToBackendMessageMeta', (_message.Message,), {
  'DESCRIPTOR' : _DEVICETOBACKENDMESSAGEMETA,
  '__module__' : 'device_to_backend_message_meta_pb2'
  # @@protoc_insertion_point(class_scope:DeviceToBackendMessageMeta)
  })
_sym_db.RegisterMessage(DeviceToBackendMessageMeta)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICETOBACKENDMESSAGEMETA._serialized_start=40
  _DEVICETOBACKENDMESSAGEMETA._serialized_end=148
# @@protoc_insertion_point(module_scope)
