# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: call_function_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.backend_to_device_message_meta_pb2 as backend__to__device__message__meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63\x61ll_function_command.proto\x12\'com.bosch.bfb.protobuf.functioncalls.v2\x1a$backend_to_device_message_meta.proto\"l\n\x13\x43\x61llFunctionCommand\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.BackendToDeviceMessageMeta\x12\x0f\n\x04name\x18\x8b\xf5\xcd\x01 \x01(\t\x12\x16\n\x0binArguments\x18\xb1\x8b\xea; \x01(\tP\x00\x62\x06proto3')



_CALLFUNCTIONCOMMAND = DESCRIPTOR.message_types_by_name['CallFunctionCommand']
CallFunctionCommand = _reflection.GeneratedProtocolMessageType('CallFunctionCommand', (_message.Message,), {
  'DESCRIPTOR' : _CALLFUNCTIONCOMMAND,
  '__module__' : 'call_function_command_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.functioncalls.v2.CallFunctionCommand)
  })
_sym_db.RegisterMessage(CallFunctionCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALLFUNCTIONCOMMAND._serialized_start=110
  _CALLFUNCTIONCOMMAND._serialized_end=218
# @@protoc_insertion_point(module_scope)
