# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: function_call_status_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.device_to_backend_message_meta_pb2 as device__to__backend__message__meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n function_call_status_event.proto\x12\'com.bosch.bfb.protobuf.functioncalls.v2\x1a$device_to_backend_message_meta.proto\"\x84\x02\n\x17\x46unctionCallStatusEvent\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.DeviceToBackendMessageMeta\x12_\n\x06status\x18\x8f\xe0\xc8\xa9\x01 \x01(\x0e\x32K.com.bosch.bfb.protobuf.functioncalls.v2.FunctionCallStatusEvent.StatusEnum\x12\x18\n\x0coutArguments\x18\xa8\x83\xc9\x8f\x01 \x01(\t\"@\n\nStatusEnum\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\x0b\n\x07\x46\x41ILURE\x10\x03P\x00\x62\x06proto3')



_FUNCTIONCALLSTATUSEVENT = DESCRIPTOR.message_types_by_name['FunctionCallStatusEvent']
_FUNCTIONCALLSTATUSEVENT_STATUSENUM = _FUNCTIONCALLSTATUSEVENT.enum_types_by_name['StatusEnum']
FunctionCallStatusEvent = _reflection.GeneratedProtocolMessageType('FunctionCallStatusEvent', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONCALLSTATUSEVENT,
  '__module__' : 'function_call_status_event_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.functioncalls.v2.FunctionCallStatusEvent)
  })
_sym_db.RegisterMessage(FunctionCallStatusEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNCTIONCALLSTATUSEVENT._serialized_start=116
  _FUNCTIONCALLSTATUSEVENT._serialized_end=376
  _FUNCTIONCALLSTATUSEVENT_STATUSENUM._serialized_start=312
  _FUNCTIONCALLSTATUSEVENT_STATUSENUM._serialized_end=376
# @@protoc_insertion_point(module_scope)
