from steps.constantfiles.constants import * # NOSONAR
SN_NAME = "?search=name=='{}'"
MSG = "/messages"
DEACTIVATE = "/{}/deactivate"
RETRY = "/{}/retry"

#RemoteMeasurement_Class
# EndPoints
RM_SIG_COL = "/remote-measurement/signalCollections"
RM_SIG_COL_SEARCH_NAME = RM_SIG_COL + SN_NAME
RM_SIG_COL_ID = RM_SIG_COL +"/{}"
RM_SIG_COL_ID_RELEASE = RM_SIG_COL_ID + "/release"
RM_SIG_COL_ID_SIGNAL_PAGE = RM_SIG_COL_ID + "/signals?page={}"
RM_SIG_COL_ID_SIGNAL_NAME = RM_SIG_COL_ID + "/signals?search=signalName=={}"
RM_SC_ID_SEARCH_NAME = RM_SIG_COL_ID + MSG + SN_NAME
RM_MEASURE_CONFIG = "/remote-measurement/measurementConfigurations"
RM_MEASURE_CONFIG_SEARCH_NAME = RM_MEASURE_CONFIG + "?search=name=={}"
RM_MEASURE_CONFIG_ID = RM_MEASURE_CONFIG + "/{}"
RM_MEASURE_CONFIG_ID_TIMEOUT = RM_MEASURE_CONFIG_ID + "/timeout"
RM_MEASURE_CONFIG_ID_PARAM = RM_MEASURE_CONFIG_ID + "/{}"
RM_MEASURE_CONFIG_ID_DRAFT = RM_MEASURE_CONFIG_ID + "/draft"
RM_MEASURE_CONFIG_ID_SOURCES = RM_MEASURE_CONFIG_ID + "/sources"
RM_MEASURE_CONFIG_ID_TRIGGERS = RM_MEASURE_CONFIG_ID + "/triggers"
RM_MEASURE_CONFIG_ID_SIGNALS = RM_MEASURE_CONFIG_ID + "/signals"
RM_MEASURE_CONFIG_ID_MSG = RM_MEASURE_CONFIG_ID + MSG
RM_MEASURE_CONFIG_ID_RELEASE_VERSION = RM_MEASURE_CONFIG_ID + "/releases/{}/signals"
RM_MEASURE_CONFIG_ID_CALCULATED_SIGNALS = RM_MEASURE_CONFIG_ID + "/calculatedSignals"
RM_MEASURE_CONFIG_ID_CALCULATED_LIST_SIGNALS = RM_MEASURE_CONFIG_ID + "/calculatedListSignals"
RM_MEASURE_CONFIG_ID_SOURCES_ID = RM_MEASURE_CONFIG_ID_SOURCES + "/{}"
RM_MEASURE_CONFIG_ID_SOURCES_ID_SIGNALS = RM_MEASURE_CONFIG_ID_SOURCES_ID + "/signals"
RM_MEASURE_CONFIG_ID_SOURCES_ID_SIGNALS_ID = RM_MEASURE_CONFIG_ID_SOURCES_ID_SIGNALS + "/{}"
RM_MEASURE_CONFIG_ID_SOURCES_ID_MSG = RM_MEASURE_CONFIG_ID_SOURCES_ID + MSG
RM_MEASURE_CONFIG_ID_SOURCES_ID_MSG_ID = RM_MEASURE_CONFIG_ID_SOURCES_ID_MSG + "/{}"
RM_MEASURE_CONFIG_ID_TRIGGERS_ID = RM_MEASURE_CONFIG_ID_TRIGGERS + "/{}"
RM_MEASURE_CONFIG_ID_TRIGGERS_ID_PHASE = RM_MEASURE_CONFIG_ID_TRIGGERS_ID + "/{}"
RM_MEASURE_CONFIG_ID_CALCULATED_SIGNAL_ID = RM_MEASURE_CONFIG_ID_CALCULATED_SIGNALS + "/{}"
RM_TEST_STEPS = "/remote-measurement/testSteps"
RM_TEST_STEPS_ID = RM_TEST_STEPS + "/{}"
RM_TEST_STEPS_ID_TARGET_FORMAT_CSV = RM_TEST_STEPS_ID + "/triggerPreview?targetFormat=CSV"
RM_TEST_STEPS_ID_MEASURE_JOB_RESULTS_CSV = RM_TEST_STEPS_ID + "/measurementJobResults/csv"
RM_TEST_STEPS_ID_TRIGGER_REASON = RM_TEST_STEPS_ID + "/trigger{}Reason"
RM_TEST_STEPS_VEHICLE_ID = RM_TEST_STEPS + "?search=vehicle.vehicleId=={}"
RM_TEST_STEPS_ELEMENTCOUNT_VEHICLE_ID = RM_TEST_STEPS + "?size={}&search=vehicle.vehicleId=={}"
RM_TEST_STEPS_MEASURE_CONFIG_ID = RM_TEST_STEPS + "?search=measurementConfiguration.measurementConfigurationId=={}"
RM_VEHICLES_ID = "/remote-measurement/vehicles/{}"
RM_VEHICLES_ID_MEASURE_JOB = RM_VEHICLES_ID + "/measurementJobs"
RM_VEHICLES_ID_MEASURE_JOB_RETRY = RM_VEHICLES_ID_MEASURE_JOB+ RETRY
RM_VEHICLES_ID_MEASURE_JOB_DEACTIVATE = RM_VEHICLES_ID_MEASURE_JOB + DEACTIVATE
RM_VEHICLES_ID_ASSIGNMENT = RM_VEHICLES_ID + "/assignments"
RM_VEHICLES_ID_ASSIGNMENTS = RM_VEHICLES_ID_ASSIGNMENT + "/"
RM_VEHICLES_ID_DEVICESLOTS_NAME_ASSIGNMENTS = RM_VEHICLES_ID + "/deviceSlots/{}/assignments"
RM_VEHICLES_ID_DEVICESLOTS_NAME_ASSIGNMENTS_ID_DEACTIVATE = RM_VEHICLES_ID_DEVICESLOTS_NAME_ASSIGNMENTS + DEACTIVATE
RM_VEHICLES_ID_DEVICESLOTS_NAME_ASSIGNMENTS_ID_ACTIVATE = RM_VEHICLES_ID_DEVICESLOTS_NAME_ASSIGNMENTS + "/{}/activate"
RM_VSG_ID = "/remote-measurement/vehicleSetupGroups/{}"
RM_VSG_ID_ASSIGNMENTS = RM_VSG_ID + "/assignments/"
RM_VSG_ID_DEVICESLOTS_NAME_ASSIGNMENTS = RM_VSG_ID + "/deviceSlots/{}/assignments"
RM_VSG_ID_DEVICESLOTS_NAME_ASSIGNMENTS_ID_DEACTIVATE = RM_VSG_ID_DEVICESLOTS_NAME_ASSIGNMENTS + DEACTIVATE
RM_VSG_ID_DEVICESLOTS_NAME_ASSIGNMENTS_ID_ACTIVATE = RM_VSG_ID_DEVICESLOTS_NAME_ASSIGNMENTS + "/{}/activate"
OTA_VEHICLE_DATA = "\\..\\..\\common\\TestData\\OTAVehicleData\\"
DATA_J1939 = "\\..\\..\\common\\VRS\\CANalization\\Data\\J1939\\"
OTA_VEHICLE_DATA_CALCULATED_SIGNAL_JSON_PATH = "common\\TestData\\OTAVehicleData\\Calculated_signal.json"
OTA_VEHICLE_DATA_DRIVER_ID_JSON_PATH = "common\\TestData\\OTAVehicleData\\DriverIds.json"

# Messages
RM_TRIGGER_JSON = "common\\TestData\\OTAVehicleData\\Trigger.json"
RM_LOGREF_MSG = "Logref: {}, Message: {}"
RM_NO_JOBID_AVAILABLE = "No measurement job IDs available for the vehicle"
RM_NOT_STARTED_TRIGGER_TIME = "Unexpected. Measurement didn't start at correct pre trigger time, Actual Value - %s with pre trigger time - %s. Expected Value - %s and pre trigger time - %s."
RM_DAF_WARNING_NAME = 'WarningId01'
RM_TRIGGER_MODE = ["Message_Variation", "COMPARE_BITMASK","OneTime_Message","COMPARE_CONSTANT","SIGNAL_INTERVAL","Signal_Variation","Daf_Warnings","Tell_Tales","DM1_Extend_Message"]
RM_BLANK_MESSAGE_DM1_EXTEND = '0x0000000000000000'