# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collect_inventory_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.backend_to_device_message_meta_pb2 as backend__to__device__message__meta__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63ollect_inventory_command.proto\x12#com.bosch.bfb.protobuf.inventory.v3\x1a$backend_to_device_message_meta.proto\"G\n\x17\x43ollectInventoryCommand\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.BackendToDeviceMessageMetaP\x00\x62\x06proto3')



_COLLECTINVENTORYCOMMAND = DESCRIPTOR.message_types_by_name['CollectInventoryCommand']
CollectInventoryCommand = _reflection.GeneratedProtocolMessageType('CollectInventoryCommand', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTINVENTORYCOMMAND,
  '__module__' : 'collect_inventory_command_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.inventory.v3.CollectInventoryCommand)
  })
_sym_db.RegisterMessage(CollectInventoryCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COLLECTINVENTORYCOMMAND._serialized_start=110
  _COLLECTINVENTORYCOMMAND._serialized_end=181
# @@protoc_insertion_point(module_scope)
