# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: software_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13software_type.proto\x12#com.bosch.bfb.protobuf.inventory.v3*J\n\x0cSoftwareType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05IMAGE\x10\x01\x12\x07\n\x03RAW\x10\x02\x12\x08\n\x04\x44\x41TA\x10\x03\x12\x0f\n\x0b\x41PPLICATION\x10\x04\x62\x06proto3')

_SOFTWARETYPE = DESCRIPTOR.enum_types_by_name['SoftwareType']
SoftwareType = enum_type_wrapper.EnumTypeWrapper(_SOFTWARETYPE)
UNKNOWN = 0
IMAGE = 1
RAW = 2
DATA = 3
APPLICATION = 4


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOFTWARETYPE._serialized_start=60
  _SOFTWARETYPE._serialized_end=134
# @@protoc_insertion_point(module_scope)
