# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ota_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ota_status.proto\x12(com.bosch.bfb.protobuf.softwareupdate.v2*\x98\x02\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0b\x44OWNLOADING\x10\x01\x12\x14\n\x10\x44OWNLOAD_FAILURE\x10\x02\x12\x14\n\x10\x44OWNLOAD_SUCCESS\x10\x03\x12 \n\x1cWAITING_FOR_UPDATE_CONDITION\x10\x04\x12\x0b\n\x07TIMEOUT\x10\x05\x12\x13\n\x0fUPDATE_REJECTED\x10\x06\x12\x0c\n\x08UPDATING\x10\x07\x12\x12\n\x0eUPDATE_FAILURE\x10\x08\x12\x12\n\x0eUPDATE_SUCCESS\x10\t\x12 \n\x1cWAITING_FOR_MANAGER_APPROVAL\x10\n\x12\x14\n\x10UPDATE_SCHEDULED\x10\x0b\x12\x12\n\x0eUPDATE_REVOKED\x10\x0c\x62\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
UNKNOWN = 0
DOWNLOADING = 1
DOWNLOAD_FAILURE = 2
DOWNLOAD_SUCCESS = 3
WAITING_FOR_UPDATE_CONDITION = 4
TIMEOUT = 5
UPDATE_REJECTED = 6
UPDATING = 7
UPDATE_FAILURE = 8
UPDATE_SUCCESS = 9
WAITING_FOR_MANAGER_APPROVAL = 10
UPDATE_SCHEDULED = 11
UPDATE_REVOKED = 12


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=63
  _STATUS._serialized_end=343
# @@protoc_insertion_point(module_scope)
