# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_status_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.device_to_backend_message_meta_pb2 as device__to__backend__message__meta__pb2
import src.resources.proto_py.softwareUpdate.ota_status_pb2 as ota__status__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19update_status_event.proto\x12(com.bosch.bfb.protobuf.softwareupdate.v2\x1a$device_to_backend_message_meta.proto\x1a\x10ota_status.proto\"\x9c\x01\n\x11UpdateStatusEvent\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.DeviceToBackendMessageMeta\x12\x44\n\x06status\x18\x8f\xe0\xc8\xa9\x01 \x01(\x0e\x32\x30.com.bosch.bfb.protobuf.softwareupdate.v2.Status\x12\x13\n\x07message\x18\x88\x80\xac\xc7\x01 \x01(\tP\x00P\x01\x62\x06proto3')



_UPDATESTATUSEVENT = DESCRIPTOR.message_types_by_name['UpdateStatusEvent']
UpdateStatusEvent = _reflection.GeneratedProtocolMessageType('UpdateStatusEvent', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESTATUSEVENT,
  '__module__' : 'update_status_event_pb2'
  # @@protoc_insertion_point(class_scope:com.bosch.bfb.protobuf.softwareupdate.v2.UpdateStatusEvent)
  })
_sym_db.RegisterMessage(UpdateStatusEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATESTATUSEVENT._serialized_start=128
  _UPDATESTATUSEVENT._serialized_end=284
# @@protoc_insertion_point(module_scope)
