# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.resources.proto_py.backend_to_device_message_meta_pb2 as backend__to__device__message__meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14update_command.proto\x1a$backend_to_device_message_meta.proto\"\x81\x02\n\rUpdateCommand\x12,\n\x04meta\x18\x85\xac\xcc\x01 \x01(\x0b\x32\x1b.BackendToDeviceMessageMeta\x12\x16\n\x0b\x61rtifactUri\x18\xc8\xc3\xed\x1a \x01(\t\x12\x13\n\x07\x62\x61seUri\x18\xa5\xee\xcd\x9e\x01 \x01(\t\x12\x1c\n\x11\x61rtifactSizeBytes\x18\xb9\x9e\xa9S \x01(\x03\x12!\n\tchecksums\x18\x90\xd9\xc0\xbe\x01 \x01(\x0b\x32\n.Checksums\x12 \n\x15\x61rtifactDecryptionKey\x18\xd5\xb8\xc8X \x01(\t\x12\x32\n\x12orchestrationLogic\x18\xe3\x94\xf7\x35 \x01(\x0b\x32\x13.OrchestrationLogic\"+\n\tChecksums\x12\x0f\n\x04sha1\x18\x85\xb2\xd7\x01 \x01(\t\x12\r\n\x03md5\x18\xfe\xca\x06 \x01(\t\"8\n\x12OrchestrationLogic\x12\"\n\x17managerApprovalRequired\x18\xb4\xc6\xc6[ \x01(\x08P\x00\x62\x06proto3')



_UPDATECOMMAND = DESCRIPTOR.message_types_by_name['UpdateCommand']
_CHECKSUMS = DESCRIPTOR.message_types_by_name['Checksums']
_ORCHESTRATIONLOGIC = DESCRIPTOR.message_types_by_name['OrchestrationLogic']
UpdateCommand = _reflection.GeneratedProtocolMessageType('UpdateCommand', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECOMMAND,
  '__module__' : 'update_command_pb2'
  # @@protoc_insertion_point(class_scope:UpdateCommand)
  })
_sym_db.RegisterMessage(UpdateCommand)

Checksums = _reflection.GeneratedProtocolMessageType('Checksums', (_message.Message,), {
  'DESCRIPTOR' : _CHECKSUMS,
  '__module__' : 'update_command_pb2'
  # @@protoc_insertion_point(class_scope:Checksums)
  })
_sym_db.RegisterMessage(Checksums)

OrchestrationLogic = _reflection.GeneratedProtocolMessageType('OrchestrationLogic', (_message.Message,), {
  'DESCRIPTOR' : _ORCHESTRATIONLOGIC,
  '__module__' : 'update_command_pb2'
  # @@protoc_insertion_point(class_scope:OrchestrationLogic)
  })
_sym_db.RegisterMessage(OrchestrationLogic)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATECOMMAND._serialized_start=63
  _UPDATECOMMAND._serialized_end=320
  _CHECKSUMS._serialized_start=322
  _CHECKSUMS._serialized_end=365
  _ORCHESTRATIONLOGIC._serialized_start=367
  _ORCHESTRATIONLOGIC._serialized_end=423
# @@protoc_insertion_point(module_scope)
