name: run contract test and publish pact

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: Enter consumer pact version to be verified
        required: true
        default: ''
        type: string
      To_environment:
        description: Enter environment to which it has to be deployed
        required: false
        default: ''
        type: string
      machine_name:
        description: Machine Name
        required: false
        type: choice
        options:
          - FE-Z1O03
          - FE2Z00XT
          - FE2Z00SN
          - FE-Z1VCG
          - LB-C-00027
          - LB-C-00024
          - LB-C-00022
          - LB-C-00025
        default: ""

jobs:
  
  Run_consumer_test:
    runs-on: 
      - self-hosted
      - ${{ inputs.machine_name }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      
      - name: Execute consumer test and publish pact
        shell: bash
        run: |
          cd API_Test/contract_test
          python run_consumer_tests_and_publish.py ${{inputs.new_version}}